#!/bin/sh

export XSECURELOCK_SAVER=saver_blank

export XSECURELOCK_FONT="Iosevka Nerd Font Mono:size=24"

export XSECURELOCK_BACKGROUND_COLOR="#1a1b26"

export XSECURELOCK_AUTH_BACKGROUND_COLOR="#1a1b26"
export XSECURELOCK_AUTH_FOREGROUND_COLOR="#c0caf5"
export XSECURELOCK_AUTH_WARNING_COLOR="#f7768e"

export XSECURELOCK_SHOW_DATETIME=1
export XSECURELOCK_DATETIME_FORMAT="%Y.%m.%d | %H:%M:%S"

export XSECURELOCK_SHOW_HOSTNAME=0
export XSECURELOCK_SHOW_USERNAME=0
export XSECURELOCK_SHOW_KEYBOARD_LAYOUT=0

export XSECURELOCK_PASSWORD_PROMPT=cursor

exec xsecurelock
